.env.example, package-lock.json, package.json, src/lib/api.ts
This PR replaces Math.random-based id generator with [nanoid](https://github.com/ai/nanoid) which looks like this:
```
ZA4xhzA2RB5pU_2mdZDp9
```
It has multiple security benefits:
* Longer ids which make brute force attacks basically impossible
* Safe randomness
* Collision resistance
I also added .env.example to save some time for future contributors
=> Replace unsafe id generator with nanoid

src/components/expense-form.tsx
Upon clicking "Mark as Paid" in the group balances tab, this redirects to the create expense page with argument "reimbursement".
The value for splitMode is not set in this instance so the UI renders the "shares" controls
To fix, explicitly set splitMode: 'EVENLY' for the reimbursement scenario.
=> Fix create expense form when clicking reimbursement link in balances page

src/app/groups/[groupId]/expenses/expense-list.tsx, src/components/expense-form.tsx, src/components/group-form.tsx
This change adds an active user option to group settings, which can be set per group. This is only saved in the devices localStorage, and therefore can be set per device.
=> Add activeUser for default payer per group

src/app/groups/[groupId]/expenses/[expenseId]/edit/page.tsx, src/app/groups/[groupId]/expenses/create/page.tsx, src/app/groups/page.tsx, src/app/groups/recent-group-list-card.tsx, src/app/groups/recent-group-list.tsx, src/app/groups/recent-groups-helpers.ts, src/lib/api.ts
~~Quick implementation for idea 1 in https://github.com/scastiel/spliit2/issues/44~~
~~Demo: https://www.loom.com/share/760c75995df94df1bdc91205631e365e?sid=5959bc98-c2a5-4332-8f2f-50f551611d05~~
~~Also happy to discuss alternative ideas for how to achieve "Indication of "Settled up" groups"~~
V2 with groupings of groups: https://www.loom.com/share/1c7edc686d0d43b5a01d3f467438def1
=> Ability to archive groups when they’re settled up

src/app/groups/[groupId]/expenses/expense-list.tsx, src/components/ui/search-bar.tsx
Fixes #51 (at least until pagination is implemented)
=> Added search bar for expense list page

README.md, next.config.js, package-lock.json, package.json, prisma/migrations/20240126214121_add_document_urls/migration.sql, prisma/migrations/20240128192510_update_document_urls/migration.sql, prisma/migrations/20240128193431_update_documents/migration.sql, prisma/migrations/20240128202400_add_doc_info/migration.sql, prisma/schema.prisma, src/app/api/s3-upload/route.ts, src/components/expense-documents-input.tsx, src/components/expense-form.tsx, src/lib/api.ts, src/lib/env.ts, src/lib/schemas.ts
Resolves #63.
Implement receipt upload for expenses, storing them to an S3 bucket provided as an environment variable.
- Handle more than images (PDF…)
=> Attach documents to expenses

README.md, package-lock.json, package.json, src/app/groups/[groupId]/expenses/create-from-receipt-button-actions.ts, src/app/groups/[groupId]/expenses/create-from-receipt-button.tsx, src/app/groups/[groupId]/expenses/expense-list.tsx, src/app/groups/[groupId]/expenses/page.tsx, src/components/expense-form.tsx, src/lib/env.ts, src/lib/utils.ts
Resolves #23.
First working version. I updated the instructions in the README, so if you want to test the feature, that should be enough. Let me know if it isn’t.
**This PR’s goal is to provide a minimum viable feature.** The UX won’t be optimal, but as long as it works as expected, that will be good enough. UX can be improved in a future PR.
=> Create expense from receipt

README.md, next.config.js, src/app/api/s3-upload/route.ts, src/components/expense-documents-input.tsx, src/lib/env.ts
Adding support for additional S3 providers to avoid vendor lock-in and for a better self-hosting experience. See #65 
I successfully tested integration with a local instance of Minio. I have not tested these changes with a standard AWS S3 setup.
=> Support for additional S3 providers

src/app/manifest.ts
This way when you install the PWA it will open to the groups page each time you open it instead of the home page.
Thanks for all the hard work on this project!
=> Update start_url to /groups page

README.md, src/app/groups/[groupId]/expenses/create-from-receipt-button-actions.ts, src/app/groups/[groupId]/expenses/create-from-receipt-button.tsx, src/components/category-selector.tsx, src/components/expense-form-actions.tsx, src/components/expense-form.tsx, src/lib/env.ts, src/lib/utils.ts
Automatically deduce category from expense title using the OpenAI API. See #72
I tried to follow the structure of the existing component and action files. Since spliit is the first project I am contributing to using Next.js and OpenAI APIs, I am particularly looking forward to feedback in this area.
The environment variable used to enable this feature could be merged with the one added in #69, e.g. `NEXT_PUBLIC_ENABLE_AI`. Similar to the receipt extraction feature, we could also add a "Beta" note to the category field. Please let me know your preferences.
=> Automatic category from expense title

src/app/groups/[groupId]/balances-list.tsx, src/app/groups/[groupId]/expenses/create-from-receipt-button.tsx, src/app/groups/[groupId]/expenses/expense-list.tsx, src/app/groups/[groupId]/reimbursement-list.tsx, src/lib/utils.ts
Added a formatting function for currency strings, in order to be able to use (and change) the format everywhere at once, and alos to add thousand separators to the formats.
I chose to do this by using the `en-US` locale (which is also used for dates), and left it hard coded for now. But since I've seen issues about translations etc, I thought perhaps a group-wide locale setting would be implemented at some point, and this makes it somewhat easy to build upon.
This makes it easier to parse larger numbers especially in the list, but also in the balances overview. This is less needed for currencies like USD and EUR, but makes more sense for other currencies like (my use case) SEK, or something like JPY.
=> Format currency with thousand separators

src/lib/schemas.ts
The `amount` input field in the "add expense" view uses the `decimal` inputMode. This renders a numbers-only keyboard that on some locales only allows the user to input a comma as the decimal point. However, the zod schema does not permit a comma as the decimal point, since `Number(value)` will return `NaN` for such numbers.
E.g. `Number("1.23") === 1.23`, but `Number("1,23") === NaN`.
Replace commas with dots in the user-inputted amount value before casting it to a JS number. The rest of the schema validation will proceed as normal.
Fixes #78
=> Fix decimal point issue in expense form schema `amount` field

src/components/expense-form.tsx
When you add a new expense you always have to start by removing the placeholder 0 value that is already there.
I added an onFocus event to select the entire value so that you can just start writing the amount immediately
=> Add onClick-event to select all to amount input

package.json
I'm not sure if I have things installed incorrectly or something on my machine, but I can't seem to run prettier normally, so I added a script for it locally so that I can just run `npm run prettier` in order to fix formatting.
I thought I'd share, but feel free to shoot down this PR if this isn't something you want in the repo.
=> Add a prettier script for ease of use (npm run prettier)

src/app/groups/[groupId]/expenses/expense-list.tsx
I have a pending purchase that I made for an upcoming trip and went ahead and added it to Spliit in preparation for it hitting my account. I noticed that it shows up in the "Earlier this year" section of the expense groups and would like it marked as a future purchase until that date arrives. I've attached before and after screenshots of my proposed changes.
Before: <img width="875" alt="Screenshot 2024-03-03 at 6 56 34 PM" src="https://github.com/spliit-app/spliit/assets/9884444/51afec47-baa9-43b5-a026-880de891bb1f">
After: <img width="852" alt="Screenshot 2024-03-03 at 6 58 01 PM" src="https://github.com/spliit-app/spliit/assets/9884444/a0809234-1181-4a59-8cf7-1aa5b178fa2c">
=> Expense list: add section for planned purchases

src/components/expense-form.tsx
Related issue #133 
Default selected user was getting updated in paid-by field, even by user select a normal reimbursement transaction.
Working Demo
https://www.loom.com/share/20b999695b23402a8a313350084cf2ca?sid=eedd3056-e1df-4c83-81ec-ddca16257ccd
=> Bug: Fixed wrong paid by Name in Reimbursement

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, next.config.js
This PR adds the necessary devcontainer configurations to support [Github Codespaces](https://github.com/features/codespaces) for this repository. It automatically sets up the Node and PostgreSQL services required to run the web app (port 3000 is also forwarded, such that code changes can directly be previewed).
=> Add devcontainer configuration for codespace support

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, next.config.js, src/app/groups/[groupId]/expenses/active-user-balance.tsx, src/app/groups/[groupId]/expenses/expense-list.tsx, src/components/money.tsx
Show the impact of an expense on the active user's balance. Relates to #131.
Note that this branch builds upon #138 as I use that for my development environment. Once the PR is in a finished state and approved, I can rebase on main.
=> Show the impact of an expense on the active user's balance

src/app/groups/[groupId]/expenses/expense-list.tsx, src/components/ui/search-bar.tsx
Simply adds an "x" button to the search bar that will show when text has been entered.
As expected, clicking on "x" will clear the search.
Motivation for this PR: I have a long list. Having to click backspace multiple times to remove the search is time consuming, since every keystroke (backspace too) triggers a new search.
=> Add "x" button to cancel search in search bar

scripts/start-local-db.sh
Without this, docker complained:
```
docker: Error response from daemon: create ./postgres-data: "./postgres-data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```
Followed recommendation from https://stackoverflow.com/questions/46526165/docker-invalid-characters-for-volume-when-using-relative-paths
=> Fix relative path docker db script

src/components/expense-form.tsx
I originally wanted to make the amount field select `onFocus`, as I wanted it to be possible to choose parts of the amount.
It was then pointed out that `onFocus` does not work for Safari, since the way onMouseUp works there deselects the text again after initially selecting it.
Therefore the choice was made to go with `onClick` instead, which seemed to work out for everyone involved, and you could still move around using the arrow keys for example if you just wanted to do edits.
Along came https://github.com/spliit-app/spliit/issues/136!
So I decided to look into getting it to work better, and more in line with the original thought.
After scouring the net I found that there is a rather simple solution for allowing this to work on Safari as well, which is to add a small delay to the …
=> change onClick to onFocus, with a slight delay for safari

Dockerfile
The custom s3 domains have stopped working for me, as the domain never gets added to the runtime next config. Next complains about the url not being whitelisted for loading images (but not in a clear way…)
This seems to have been the case since https://github.com/spliit-app/spliit/pull/91 which removed files (among other fixes) in order to make the the Docker image smaller.
The easy fix is just adding back the `next.config.js` to the runtime environment, since this fix was already added in https://github.com/spliit-app/spliit/pull/71 in order to get the custom domains working in the first case.
=> copy the next.config.js in order to get custom domains working (for alternative s3 providers) again

prisma/migrations/20240414135355_add_activity_log/migration.sql, prisma/schema.prisma, src/app/groups/[groupId]/activity/activity-item.tsx, src/app/groups/[groupId]/activity/activity-list.tsx, src/app/groups/[groupId]/activity/page.tsx, src/app/groups/[groupId]/edit/page.tsx, src/app/groups/[groupId]/expenses/[expenseId]/edit/page.tsx, src/app/groups/[groupId]/expenses/create-from-receipt-button.tsx, src/app/groups/[groupId]/expenses/create/page.tsx, src/app/groups/[groupId]/expenses/expense-list.tsx, src/app/groups/[groupId]/group-tabs.tsx, src/app/groups/[groupId]/layout.tsx, src/app/groups/[groupId]/share-button.tsx, src/components/expense-form.tsx, src/components/group-form.tsx, src/lib/api.ts, src/lib/utils.ts
This PR adds a basic implementation for an activity log in each group. Currently 4 types of activity are logged: updating the group settings and creating/updating/deleting an expense. If an active user is configured, the activity message includes the name of that active user. If #95 is approved, the "infinite scroll" feature can also be applied to this activity log (the implementation here is derived from the expense list).
Related issues are #15, #103 and #106.
=> Add basic activity log

src/app/groups/[groupId]/expenses/expense-list.tsx, src/app/groups/[groupId]/stats/totals-group-spending.tsx, src/app/groups/[groupId]/stats/totals-your-share.tsx, src/app/groups/[groupId]/stats/totals-your-spending.tsx, src/components/expense-form.tsx, src/lib/schemas.ts
A feature which I don't need very often, but dearly miss when I need it, is to **enter a group income**.
Imagine a flight you paid for your trip with Jane and Jack gets cancelled. You are receiving $90 refund from the booking agency on behalf of the group. How would you enter that?
- What I did was to enter 2 reimbursements with $30 each: "Jane --> yourself" and "Jack --> yourself". This is not only ugly and weird (calculate splits and record cash flows in the opposite direction) but also wrong: The total group balance is not reduced by $90 as ist should be.
- Another option would be to remove the original expense completely. But this is also wrong because it messes with the transaction history.
Adding a proper income is actually very simple. It's just an **expense with a negative …
=> Add support for group income (= negative expenses)

src/app/groups/[groupId]/expenses/expense-list.tsx, src/lib/utils.ts
This is the PR to solve the issue #185 
The PR introduces a `normalizeString` function, which it is used on the `SearchBar` to allow more expenses to be found without an exact match.
**Current Behavior**
Expense entry with title "Park Güell". When Search content is `guell` the expense is not found since `u` is not included in `ü`.
**New Behavior**
Expense entry with title "Park Güell". When Search content is `guell` the expense is found since the function removes all special characters from both search input and expense. ("Park Güell" becoming "park guell")
=> Increase fuzzines of search results

scripts/start-local-db.sh
I wondered why this script gave me `postgres is already running, doing nothing`. It was because another project was already running a container with `postgres` in its name.
Using more unique name like `spliit-db` solved the issue. Using `spliit-db` makes it clear which project is using this container when making `docker ps`.
=> Use unique name for postgres container

src/lib/balances.ts
Previously, after a group participant executed a suggested reimbursement, rerunning `getSuggestedReimbursements()` could return a completely new list of suggestions.
With this change, `getSuggestedReimbursements()` should now be stable: if it returns a graph with n edges, and then a repayment is made according to one of those edges, when called again, it should now return the same graph but with that one edge removed.
The trick is that the main logic in `getSuggestedReimbursements()` does not rely on `balancesArray` being sorted based on `.total` values, only that the array gets partitioned into participants with credit first and then participants with debt last. After a repayment is made, re-sorting based on `.total` values would result in a new order hence new suggestions, but sorting …
=> Make recalculation stable across repayments in suggested reimbursements

src/components/expense-form.tsx
- Don't load default split options after displaying an existing expense
- Re-validate form after changing the "paidFor" selection. 
This fixes the error message "The expense must be paid for at least one participant." after clicking "Select None" and the selecting one participant.
=> Fix: Correctly display loaded expense

jest.config.ts, package-lock.json, package.json, src/app/groups/[groupId]/expenses/create-from-receipt-button-actions.ts, src/lib/utils.test.ts, src/lib/utils.ts
To ensure the formatter works as expected, I also set up testing. The test cases ended up taking a lot more time than the fix itself, but I wanted to make sure not to introduce any other unexpected formatting bug.
As a mostly unrelated change, I needed to change the GPT model used as I was getting depreciation errors during development.
Fixes #87 @RayBB 
Fixes #140 @Phlipde
Fixes #121 @webzit
Do the changes from #81 still work as expected @justcallmelarry?
=> Fix amount preview for scanned receipts

messages/de-DE.json, messages/en-US.json, messages/es.json, messages/fi.json, messages/fr-FR.json, messages/it-IT.json, messages/ru-RU.json, messages/ua-UA.json, messages/zh-CN.json, src/components/expense-form.tsx
This pull request adds a translation for the word "Reimbursement" used as a title in the expense form, when marking suggested reimbursements as paid.
The translation has been added to all languages supported in the main branch as of today (10.14.24).
This includes:
- english
- finnish
- french
- spanish
- german
- chinese
- russian
- italian
- ukrainian
This change improves the localization of the application and provides a better user experience for speakers of these languages.
=> Fix missing translation for expense title for reinbursement in expense-form

.env.example, src/components/group-form.tsx, src/lib/env.ts
In this PR I´ve added a env parameter that can be used to define a default currency symbol on group creation. The symbol can still be changed on creation by inserting another symbol into the input field.
The following variables were added:
| VAR name   |      Default      |  Description |
|----------|:-------------|------|
| NEXT_PUBLIC_DEFAULT_CURRENCY_SYMBOL |  none | This parameter can be used to define a default currency symbol that will be used on group creation. |
ToDo:
Currently the env var is defined directly via `currency: process.env.NEXT_PUBLIC_DEFAULT_CURRENCY_SYMBOL || '',` and not via the env.ts file. It is working fine, but we are missing the validation of zod. I wasn´t able to define the variable via the env.ts file, because some of the vars are missing on the clientside. …
=> Feature: Default currency symbol

messages/en-US.json, src/app/groups/[groupId]/expenses/documents-count.tsx, src/app/groups/[groupId]/expenses/expense-card.tsx, src/lib/api.ts
We can have attachments for expenses, but in expenses list we do not show if a particular expense has an attachment or not. Relates to [#238](https://github.com/spliit-app/spliit/issues/238)
_**Before:**_
**_After:_**
Expense has attachments:
Mobile:
No attachments:
=> feat(expense-list): Display the attachment count only when the expense includes attachments

src/lib/utils.ts
Fixes time mismatch mentioned in #217 (utc timezone hardcoded in format date util fn)
=> fix: utc timezone used in activity tracker

src/lib/schemas.ts
This PR is to fix this issue #290 
The current validation logic is not restricting the expense creation when the amount is "0".
After:
=> fix the amount validation while creating an expense

messages/de-DE.json, messages/en-US.json, messages/es.json, messages/fi.json, messages/fr-FR.json, messages/it-IT.json, messages/pl-PL.json, messages/ro.json, messages/ru-RU.json, messages/ua-UA.json, messages/zh-CN.json, messages/zh-TW.json, package-lock.json, package.json, src/app/groups/[groupId]/expenses/export/csv/route.ts, src/app/groups/[groupId]/expenses/page.client.tsx, src/app/groups/[groupId]/export-button.tsx
This pull request introduces a new feature that allows users to export group data as a CSV file. The feature enhances accessibility and usability by providing an easily shareable and analyzable data format.
Addressed Issue: [Feature request: Export Data as a User-Friendly CSV File (similar to Splitwise) #282](https://github.com/spliit-app/spliit/issues/287)
- **CSV Export Functionality:** Users can export group expenses to a CSV file with a single click.
- **Comprehensive Data Structure:** The exported CSV includes:
- **Date**: When the expense occurred.
- **Description**: Details of the expense.
- **Category**: Expense category.
- **Currency**: Currency used.
- **Cost**: Total amount of the expense.
- **Is Reimbursement**: Whether the expense is a reimbursement or not.
-  **Split mode**: …
=> Feat: Add export to CSV support

src/app/groups/[groupId]/expenses/export/json/route.ts
According to the [getGroupExpenses](https://github.com/spliit-app/spliit/blob/72ad0a4c90054cdb28c115ccd2d144b946e58d51/src/lib/api.ts#L297), the UI appears to sort expenses by expense date first, and then by creation date if multiple expenses have the same expense date.
This PR adds a `createdAt` column to the export feature and sorts the data in ascending order using the same logic as the UI.
=> Ensure the exported data is sorted by the expense date

messages/pl-PL.json
Minor updates to Polish translation:
- in some contexts the phrasing was a bit misleading
- There was missing field for default reimbursement title (`ExpenseForm.reimbursement`)
=> Fixes in polish translation

messages/de-DE.json, messages/en-US.json, messages/es.json, messages/fr-FR.json, messages/it-IT.json, messages/ru-RU.json, messages/ua-UA.json, messages/zh-CN.json, src/app/groups/[groupId]/expenses/create-from-receipt-button-actions.ts
This PR corrects a misspelled property name in several language JSON files, including German. The same typo was partially addressed in PR #303 (for German only), but this PR extends the fix to all affected language files to ensure correct translations display to users.
It also fixes a minor typo in the open AI prompt in src/app/groups/[groupId]/expenses/create-from-receipt-button-actions.ts
=> Fix typo in translation files

scripts/container-entrypoint.sh
This will replace the `sh` process from the container entrypoint with the node process as PID 1, to properly handle SIGTERM signals and gracefully shut down the container.
Currently, `sh` will intercept any signals and not forward them to node, leaving the container in the terminating state before docker force kills it after the 10s grace period. This means that db connections won't be closed and that requests will get interrupted during shutdown.
=> Use exec in container entryptoint to replace the shell process

messages/de-DE.json, messages/en-US.json, messages/es.json, messages/fr-FR.json, messages/it-IT.json, messages/pl-PL.json, messages/ro.json, messages/ru-RU.json, messages/ua-UA.json, messages/zh-CN.json, messages/zh-TW.json
Discovered when using the official Spliit instance:
https://spliit.app/groups/ycyaejYHrUW6O9CVtwugA/expenses
Note that only the i18n files contain the typo. The code that builds the i18n key and performs the translation has the correct spelling:
https://github.com/spliit-app/spliit/blob/9302a32f4c0e3081985f6410debed7f863bfd67b/src/app/groups/%5BgroupId%5D/expenses/expense-list.tsx#L28
https://github.com/spliit-app/spliit/blob/9302a32f4c0e3081985f6410debed7f863bfd67b/src/app/groups/%5BgroupId%5D/activity/activity-list.tsx#L24
Thanks for making this app!
=> Fix typos in i18n keys for Expenses.Groups.lastYear and Activity.Groups.lastYear for most locales

compose.yaml
now you can do:
1. clone
2. run the app
```
cp container.env.example container.env
docker compose build
docker compose up -d
```
=> docker compose: allow to build container and use interanl network

messages/de-DE.json, messages/en-US.json, messages/es.json, messages/fi.json, messages/fr-FR.json, messages/it-IT.json, messages/pl-PL.json, messages/ro.json, messages/ru-RU.json, messages/ua-UA.json, messages/zh-CN.json, prisma/migrations/20241103205027_add_recurring_expenses/migration.sql, prisma/schema.prisma, src/app/groups/[groupId]/expenses/expense-form.tsx, src/app/groups/[groupId]/expenses/export/json/route.ts, src/lib/api.ts, src/lib/schemas.ts
- Closes issue #5 
- An expense can be created with a recurrence/repeating rule, and subsequent expenses will be created
- Deleting the most recent expense causes no further repeating expenses to be created
- Changing the most recent expense to no longer repeat causes no further repeating expenses to be created
- Changing the recurrence rule of the most recent expense causes all subsequent expenses to adopt the same recurrence
- Creating a monthly expense on the 29th, 30th, or 31st will not cause the expense to consistently be created for that date
- If an expense is created on any of these 3 dates, it will eventually adopt the largest date available in the next month if the target date is not available
- Ex 1
- A monthly expense is initially created on January 31st, 2024
- The next 3 …
=> Add recurring expense functionality

messages/de-DE.json, messages/en-US.json, src/app/groups/[groupId]/expenses/expense-form.tsx
The object `recurrenceRule` was in the wrong section. Also, the strings in it were not translated.
The placeholder for the "paid by" field was hard-coded in English. I also made this translatable and added a translation to de-DE. Translations to other languages should be done as well, but I don't know what process you have for that, if you have one. (The issue with `recurrenceRule` is also an issue in other languages, by the way.)
=> Fix missing translation string in de-DE

messages/de-DE.json
Hi, I've noticed missing translations for:
- ExpenseForm.Expense.recurrenceRule.label
- ExpenseForm.Expense.recurrenceRule.description
- ExpenseForm.Expense.recurrenceRule.none
- ExpenseForm.Expense.recurrenceRule.daily
- ExpenseForm.Expense.recurrenceRule.weekly
- ExpenseForm.Expense.recurrenceRule.monthly
and added them.
I also adjusted some the translations that were previously english for:
- ExpenseForm.Income.recurrenceRule.label
- ExpenseForm.Income.recurrenceRule.description
- ExpenseForm.Income.recurrenceRule.none
- ExpenseForm.Income.recurrenceRule.daily
- ExpenseForm.Income.recurrenceRule.weekly
- ExpenseForm.Income.recurrenceRule.monthly
=> update de-DE translation for recurrenceRule

messages/en-US.json, package-lock.json, package.json, prisma/migrations/20250405152338_add_group_currency_code/migration.sql, prisma/schema.prisma, src/app/groups/[groupId]/balances-list.tsx, src/app/groups/[groupId]/balances/balances-and-reimbursements.tsx, src/app/groups/[groupId]/expenses/active-user-balance.tsx, src/app/groups/[groupId]/expenses/create-from-receipt-button.tsx, src/app/groups/[groupId]/expenses/expense-card.tsx, src/app/groups/[groupId]/expenses/expense-form.tsx, src/app/groups/[groupId]/expenses/expense-list.tsx, src/app/groups/[groupId]/expenses/export/csv/route.ts, src/app/groups/[groupId]/expenses/export/json/route.ts, src/app/groups/[groupId]/reimbursement-list.tsx, src/app/groups/[groupId]/stats/totals-group-spending.tsx, src/app/groups/[groupId]/stats/totals-your-share.tsx, src/app/groups/[groupId]/stats/totals-your-spending.tsx, src/app/groups/[groupId]/stats/totals.tsx, src/components/currency-selector.tsx, src/components/group-form.tsx, src/components/money.tsx, src/lib/api.ts, src/lib/currency-data.json, src/lib/currency.ts, src/lib/schemas.ts, src/lib/utils.test.ts, src/lib/utils.ts, src/scripts/generateCurrencyData.ts, tsconfig.json
This change is to be able to define an optional main currency selection to groups, for the conversion rate feature, based on [this comment](https://github.com/spliit-app/spliit/issues/53#issuecomment-1901749100).
Originally this PR was supposed to be part of the currency conversion feature, but the PR would have been a bit large.
Currency code in a group influences how amounts are displayed and handled in transactions. The "amount" value is treated as the number of minor units in the currency. For example, "1500" is treated as "$15.00" if the currency is USD, but "ISK 1500" if the currency is ISK (as some currencies like ISK, JPY do not have any cents).
Choosing a currency also enables display of the amounts with the correct symbol according to the locale.
For example:
The supported …
=> Add main currency code for groups
